README.md

Add link to the [Trail](https://github.com/panesofglass/trail) DSL for writing Blazor markup in F#.

Add Trail to Libraries

---

README.md

BlazorConfirm is a JavaScript wrapper for `Window.Confirm`. Can execute code on modal confirmation.

Adding BlazorConfirm.

---

README.md

* Added new feature on description
* Link to demo as other demo links: "(Demo)"

BlazorConfirm, Added new feature on description

---

README.md

Library BlazorSplit - Resizeable split views.

BlazorSplit

---

README.md

Added BlazorFileSaver https://github.com/IvanJosipovic/BlazorFileSaver

Added BlazorFileSaver

---

README.md

If you find it a worthy addition, then I wouldn't mind having this in the samples for a PWA capable example.

Add ZoraGen Blazor to samples

---

README.md

New version release now includes a new Authentication Grant Flow, thanks

Please update Blazor.Auth0 description

---

README.md

Please consider adding Grid.Blazor to the Libraries section.

Add Grid.Blazor component

---

README.md

Added link to Flexor which is a Blazor implementation of [Angular Flex Layout](https://github.com/angular/flex-layout).
Angular flex layout was an immensely powerful tool when I was working in Angular 2+, and I fell in love with it.  While Blazor does not support directives, I implemented declarative and highly configurable components which allow the closest facsimile I can get currently in Blazor.
Thanks,
~Derek

Updated README.md with link to Flexor.

---

README.md

Open-source application that illustrates (and includes online demo) of key Blazor application features including file upload / download, table pagination, authentication with JWT, and configuration of Azure DevOps for a client-side Blazor application build and deployment to Azure.

Add BlazorCRUD to Sample Projects Section

---

README.md

Added BlazorBeerCalculator to demos list. It's open-source project in Github. Added also link to live demo site.

Added my Blazor beer calculator demo

---

README.md

Client/Server game using Websockets (SignalR), with a MongoDB API, and Docker deployment (docker-compose).

Add "Blazor 20 Questions" to Sample Projects section

---

README.md

[Radzen.Blazor](https://github.com/akorchev/razor.radzen.com/) - FREE Native UI components for Blazor. DataGrid, DataList, Tabs, Dialog and more. ([Demo](https://razor.radzen.com/)).

Add "Radzen.Blazor" to Libraries & Extensions section

---

README.md

The [BlazorIntersectionObserver](https://github.com/ljbc1994/BlazorIntersectionObserver) package is a wrapper for the Intersection Observer API, it also contains a component for easier intersection observation.

Add "BlazorIntersectionObserver" to Libraries & Extensions section

---

README.md

I deprecated Blazorous in favor of BlazorStyled therefore:
* Removed the link to Blazorous
* Added a link to BlazorStyled

Replace Blazorous with BlazorStyled

---

README.md

Added Rudder library - a state container for Blazor.

Added Rudder library - a state container for Blazor.

---

README.md

Built on MatBlazor and BlazorWithIdentity. The other options I found within this directory were out of date and lacking functionality. I am looking to grow contributors for open-source project. Thanks.

BlazorBoilerplate

---

README.md

Awesome component by @chrissainty

Add "Blazored Typeahead" to Libraries & Extensions

---

README.md

Adding BlazorFabric - port of Microsoft Fabric UI.
This is not the same version as the other port of Microsoft Office Fabric UI.  This one is all new.  Thanks!

Adding BlazorFabric - port of Microsoft Fabric UI to README.md

---

README.md

[Blagario](https://github.com/ctrl-alt-d/Blagario) is a agario like game just with blazor (core3 preview6), html and css ( no canvas )
Current status is scaffolding and includes: 
* Multiplayer (multiple user at a time)
* Mouse position tracking (cell goes to mouse)
* Dependency injection to add player as transient (one cell for each player) and world as singleton (one world for all players)
* Draw agar viruses and cells.
A readable [todo list](https://github.com/ctrl-alt-d/Blagario/issues/1) is available as issue and open to everybody who wants to collaborate.

Add blagario

---

README.md

I want to add a project that I have been working on for my company. Hope to join the list of awesomeness ❤️

Added Gjallarhorn as a sample project

---

README.md

I added a new library link for a library that I made and am actively working on. 
BlazorQuery is a Blazor Library that wraps jQuery completely in C# so that DOM Manipulation, Ajax, etc, can be done directly without leaving the comfort of C#.

Added BlazorQuery to Library List

---

README.md

A tutorial showing how to use [GeneticSharp](https://github.com/giacomelli/GeneticSharp) (genetic algorithms) and Blazor to solve the TSP (Travelling salesman problem): http://diegogiacomelli.com.br/tsp-with-geneticsharp-and-blazor/

Added "TSP with GeneticSharp and Blazor"

---

README.md

Add stars to blagario

---

README.md

@AdrienTorris and @chrissainty ,
Just for test I have update all stars for all repositories. What you think about it?

Set Stars for all github repositories

---

README.md

BlazorDateRangePicker is a recently developed Blazor component for choosing date ranges and dates. It is a port of js [DateRangePicker](https://github.com/dangrossman/daterangepicker/), rewritten using C#, compatible with both client-side and server-side Blazor.

Add BlazorDateRangePicker to Components section

---

README.md

* Updated the URIs for BlazorStrap and BlazorStyled
* Added BlazorTypography to "Tools" section
Note: I didn't know what order that section is in, so I added BlazorTypography right under BlazorStyled. I hope that is ok.

Updated URIs and Added BlazorTypography

---

README.md

Added Blazor Tips and Tricks

---

README.md

Added BlazorGoogleMaps to list

Added BlazorGoogleMaps to list

---

README.md

Added BlazorPong

---

README.md

RapidCMS is a Blazor framework which allows you to build a responsive and flexible CMS purely from code. It provides a basic set of editors and controls, and is fully customisable.

Added RapidCMS

---

README.md

Added Youtube playlist with Blazor related videos in spanish in the Other Languages section.

Added youtube videos in spanish

---

README.md

Added BlazorPoint a Blazor on SharePoint Github Repo.

Added BlazorPoint

---

README.md

Thank you for putting this excellent resource together!

Minor capitalization and spelling corrections

---

README.md

Blazor.LoadingIndicator is a helper library developed for libs that depend on web services or slow calculation. It helps to lower the amount of boilerplate needed for a nice responsive feeling UI.

Add Blazor.LoadingIndicator to Libraries section

---

README.md

Added links to recommended visual studio for Mac, windows and latest non-preview .Net core 3.0 SDK

Update blazor intro requirements

---

README.md

BlazorTictactoe is simple implementation of Tic-tac-toe game in Blazor WebAssembly. 
I believe this implementation uses good component design and communication pattern.

add: BlazorTictactoe under games

---

README.md

BlazorGrpc takes advantage of `.proto` file generation and an adhoc gRPC API gateway to enable a Blazor WebAssembly app to communicate with gRPC backend APIs as well as share all of the same request/response object models.

Added BlazorGrpc

---

README.md

Adding Sample Projects > Other > Blazor Fire Calculators.  With description and demo.

Adding Blazor Fire Calculators to Sample Projects

---

README.md

Change 'Blazor Fire Calculators' description and add 'Create PWA using Blazor' article

Add PWA Article

---

README.md

https://knowledge-base.havit.eu/2019/11/02/blazor-component-lifecycle-diagram/

Blazor Component Lifecycle Diagram

---

README.md

Added BlazorTable
Updated BlazorFileSaver with GitHub Badge and Link to Demo

Added BlazorTable and updated BlazorFileSaver

---

README.md

Added Getting Started with Blazor: All There is to Know From the Experts

All There is to Know From the Experts

---

README.md

I added a link to my Nuget package and code for DataJuggler.Blazor.FileUpload and sample project.

Added DataJuggler.Blazor.FileUpload Nuget package, code and sample project.

---

README.md

A small sample app to demo Blazor WebAssembly with 
- Excel export
- PWA with offline-first
- LocalStorage

Adds dcidr sample app

---

README.md

Previous link points to readme which says project has moved to new location

Updated link to Howler.Blazor

---

README.md

Added stars and last commit to Cortex.Net.
Added documentation link.

Updated Cortex.Net

---

README.md

This is the first Blazor article related to Azure IoT Edge. 
I show how to create a container running Blazor and attach it to the Azure IoT Edge routing so it's a full member of the logic running op an Edge device.

Add article "Attach Blazor to Azure IoT Edge routing, showing live message feed"

---

README.md

Zoom and move image with Blazor using mouse wheel and mouse drag - minimal javascript.

Add BlazorWheelZoom component

---

README.md

My book is written in German. I am not sure if this is OK for your list. 
Thanks
Holger
* [ASP.NET Core Blazor 5.0: Blazor WebAssembly und Blazor Server: Moderne Single-Page-Web-Applications mit .NET, C# und Visual Studio](https://www.amazon.de/exec/obidos/ASIN/393427935X/itvisions-21) - German book on Blazor (Published September 15, 2020 with montly Updates).

Added book

---

README.md

I have added an entry for my book on Blazor: https://www.amazon.com/Microsoft-Blazor-Building-Applications-Beyond/dp/1484278445

Add Microsoft Blazor Book
